using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Assist.SearchEngine
{
    public class DataItem
    {
        #region Data Members

        /// <summary>
        /// Get the unique string to distinguish itself from others.
        /// The id is generated by the data source. We can detect where the data item is from by the Id.
        /// 
        /// The Id must be different for all the items.
        /// </summary>
        public String Id { get; set; }

        /// <summary>
        /// The key of the data source. It is used for quick source.
        /// </summary>
        public String Key { get; set; }

        /// <summary>
        /// The tile of this item.
        /// </summary>
        public String Title { get; set; }

        /// <summary>
        /// The value of this items.
        /// </summary>
        public String Value { get; set; }

        /// <summary>
        /// The comments for this item.
        /// </summary>
        public String Comments { get; set; }

        /// <summary>
        /// The labels attached to this item. They are separated by the semicolon.
        /// 
        /// Such as Label1;Label2;Label3
        /// </summary>
        public String Labels { get; set; }

        /// <summary>
        /// Record how many times this item is accessed.
        /// </summary>
        public UInt32 AccessCounter { get; set; }

        #endregion

        public DataItem()
        {
            Id = "";

            Key = "";
            Title = "";
            Value = "";
            Comments = "";

            Labels = "";
            AccessCounter = 0;
        }

        public DataItem(DataItem src)
        {
            CloneFrom(src);
        }

        public void CloneFrom(DataItem src)
        {
            Id = src.Id.Clone() as String;

            Key = src.Key.Clone() as String;
            Title = src.Title.Clone() as String;
            Value = src.Value.Clone() as String;
            Comments = src.Comments.Clone() as String;

            Labels = src.Labels.Clone() as String;
            AccessCounter = src.AccessCounter;
        }

    }
}
